### ISSUE TITLE
Name too similar to another project.

### ISSUE THREAD

**Issue by RedsTom** [Pyscord/Pyscord#2]
Hello, as a faithful supporter of the [Piscord](https://github.com/Astremy/piscord) project, I think it's not fair to take this name.

Effectively, you could choose another name, because actually, the two names are too similar and can confuse the people who can use Piscord, or redirect the people searching for Pyscord on Piscord.

So, for the better understanding of everyone, can you please change the name of your library not to be too similar to Piscord.

Best regards,
RedsTom.

**Comment by Sigmanificient** [comment]
Hi, it's seems that your have a issue with our project named `Pyscord` to the project name `Piscord`.

However, when searching for the name of the project we didn't found that `Piscord` name.
Domain names have already been bought so we cannot going back.
