### ISSUE TITLE
voler n'est pas bon

### ISSUE THREAD

**Issue by GravenilvecTV** [Pyscord/Pyscord#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Sly-Little-Test** [comment]
Hello. I translated your issue title with Google Translate and it looks like you mean "stealing is bad". This project did **not** steal the name from other projects (if you are about the name). Also, please use English.

**Comment by Sigmanificient** [comment]
As Sly-Little-Test stated, this project name didn't meant to cause any issues with other one projects.

However, we already bought domain names, it will be very hard for us to change our name.
We are currently discussing with our team on what we will do and if name change is possible.
